Switching mig-controller to go mod
* Having to set specific values to keep compatability
* pinning is done w/ replaces
* Adding go.sum
* fixing generation to use controller-gen
* Moving an interface from apis to the package that uses the interface.

diff --git a/vendor/go.opencensus.io/Makefile b/vendor/go.opencensus.io/Makefile
--- a/vendor/go.opencensus.io/Makefile
+++ b/vendor/go.opencensus.io/Makefile
@@ -8,7 +8,11 @@ ALL_PKGS := $(shell go list $(sort $(dir $(ALL_SRC))))
 GOTEST_OPT?=-v -race -timeout 30s
 GOTEST_OPT_WITH_COVERAGE = $(GOTEST_OPT) -coverprofile=coverage.txt -covermode=atomic
 GOTEST=go test
+<<<<<<< HEAD
+GOIMPORTS=goimports
+=======
 GOFMT=gofmt
+>>>>>>> cbc9bb05... fixup add vendor back
 GOLINT=golint
 GOVET=go vet
 EMBEDMD=embedmd
@@ -17,6 +21,16 @@ TRACE_ID_LINT_EXCEPTION="type name will be used as trace.TraceID by other packag
 TRACE_OPTION_LINT_EXCEPTION="type name will be used as trace.TraceOptions by other packages"
 README_FILES := $(shell find . -name '*README.md' | sort | tr '\n' ' ')
 
+<<<<<<< HEAD
+.DEFAULT_GOAL := imports-lint-vet-embedmd-test
+
+.PHONY: imports-lint-vet-embedmd-test
+imports-lint-vet-embedmd-test: imports lint vet embedmd test
+
+# TODO enable test-with-coverage in tavis
+.PHONY: travis-ci
+travis-ci: imports lint vet embedmd test test-386
+=======
 .DEFAULT_GOAL := fmt-lint-vet-embedmd-test
 
 .PHONY: fmt-lint-vet-embedmd-test
@@ -25,6 +39,7 @@ fmt-lint-vet-embedmd-test: fmt lint vet embedmd test
 # TODO enable test-with-coverage in tavis
 .PHONY: travis-ci
 travis-ci: fmt lint vet embedmd test test-386
+>>>>>>> cbc9bb05... fixup add vendor back
 
 all-pkgs:
 	@echo $(ALL_PKGS) | tr ' ' '\n' | sort
@@ -44,6 +59,17 @@ test-386:
 test-with-coverage:
 	$(GOTEST) $(GOTEST_OPT_WITH_COVERAGE) $(ALL_PKGS)
 
+<<<<<<< HEAD
+.PHONY: imports
+imports:
+	@IMPORTSOUT=`$(GOIMPORTS) -l $(ALL_SRC) 2>&1`; \
+	if [ "$$IMPORTSOUT" ]; then \
+		echo "$(GOIMPORTS) FAILED => goimports the following files:\n"; \
+		echo "$$IMPORTSOUT\n"; \
+		exit 1; \
+	else \
+	    echo "Imports finished successfully"; \
+=======
 .PHONY: fmt
 fmt:
 	@FMTOUT=`$(GOFMT) -s -l $(ALL_SRC) 2>&1`; \
@@ -53,6 +79,7 @@ fmt:
 		exit 1; \
 	else \
 	    echo "Fmt finished successfully"; \
+>>>>>>> cbc9bb05... fixup add vendor back
 	fi
 
 .PHONY: lint
@@ -91,6 +118,12 @@ embedmd:
 
 .PHONY: install-tools
 install-tools:
+<<<<<<< HEAD
+	go get -u golang.org/x/lint/golint
+	go get -u golang.org/x/tools/cmd/cover
+	go get -u golang.org/x/tools/cmd/goimports
+=======
 	go get -u golang.org/x/tools/cmd/cover
 	go get -u golang.org/x/lint/golint
+>>>>>>> cbc9bb05... fixup add vendor back
 	go get -u github.com/rakyll/embedmd
